import type { DockingResult, ResearchProject, ProcessingJob, SystemStats, Activity } from "./types"

export const mockDockingResults: DockingResult[] = [
  {
    id: "dock_001",
    protein: {
      pdbId: "1M17",
      name: "EGFR Kinase Domain",
      uniprotId: "P00533",
      organism: "Homo sapiens",
    },
    ligand: {
      name: "Erlotinib",
      smiles: "COc1cc2ncnc(Oc3ccc(F)c(Cl)c3)c2cc1OCCOC",
      molecularWeight: 393.44,
      logP: 3.2,
      hBondDonors: 1,
      hBondAcceptors: 6,
    },
    simulation: {
      program: "vina",
      version: "1.2.3",
      parameters: { exhaustiveness: 8, num_modes: 9 },
      runtime: 342,
      timestamp: new Date("2024-01-15T10:30:00"),
    },
    binding: {
      affinity: -9.2,
      ki: 0.00018,
      bindingMode: 1,
      poseCount: 9,
      bestPose: {
        coordinates: [[0, 0, 0]],
        interactions: [
          { type: "hydrogen-bond", residues: ["Met793", "Lys745"], distance: 2.8 },
          { type: "hydrophobic", residues: ["Leu788", "Val726"], distance: 3.5 },
        ],
      },
    },
    aiTags: {
      proteinFamily: ["Tyrosine Kinase", "EGFR Family"],
      therapeuticArea: ["Oncology", "Lung Cancer"],
      bindingStrength: "strong",
      druggability: "high",
      noveltyScore: 0.82,
    },
    storage: {
      cid: "QmX7kJ9mN5pQ8rS2tU3vW4xY6zA1bC2dE3fG4hH5iI6jJ",
      solanaTx: "5Jm8KqPnYvXz4Wq7Rp9Ls3Mt6Nk2Op8Qr5St1Uv4Wx7",
      dataHash: "0x7a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a",
      fileReferences: {
        original: "egfr_erlotinib_vina.pdbqt",
        processed: "egfr_erlotinib_processed.pdb",
        visualization: "egfr_erlotinib_viz.png",
      },
    },
    metadata: {
      createdBy: "user_001",
      createdAt: new Date("2024-01-15T10:30:00"),
      updatedAt: new Date("2024-01-15T10:35:00"),
      projectId: "proj_001",
      validated: true,
    },
  },
  {
    id: "dock_002",
    protein: {
      pdbId: "6LU7",
      name: "SARS-CoV-2 Main Protease",
      uniprotId: "P0DTD1",
      organism: "SARS-CoV-2",
    },
    ligand: {
      name: "Nirmatrelvir",
      smiles: "CC(C)(C)C(=O)NC(C(C)C)C(=O)N[C@@H](C(=O)N[C@H]1CCCC1)",
      molecularWeight: 499.53,
      logP: 2.1,
      hBondDonors: 4,
      hBondAcceptors: 5,
    },
    simulation: {
      program: "glide",
      version: "2023-1",
      parameters: { precision: "XP", num_poses: 10 },
      runtime: 580,
      timestamp: new Date("2024-01-14T15:20:00"),
    },
    binding: {
      affinity: -10.4,
      ki: 0.000021,
      bindingMode: 1,
      poseCount: 10,
      bestPose: {
        coordinates: [[0, 0, 0]],
        interactions: [
          { type: "hydrogen-bond", residues: ["His163", "Glu166", "Gln189"], distance: 2.6 },
          { type: "hydrophobic", residues: ["Met49", "Met165"], distance: 3.2 },
        ],
      },
    },
    aiTags: {
      proteinFamily: ["Cysteine Protease", "3C-like Protease"],
      therapeuticArea: ["Infectious Disease", "COVID-19"],
      bindingStrength: "strong",
      druggability: "high",
      noveltyScore: 0.95,
    },
    storage: {
      cid: "QmY8lK0nO6qR9sT4uV5wX7yZ0aB1cC3dD4eE5fF6gG7hH",
      solanaTx: "6Kn9LrQoZwYa5Xs8Sq4Nu7Pv2Mr9Nt1Pq6Rs2Uv5Xy8",
      dataHash: "0x8b0a9c8e7f6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f",
      fileReferences: {
        original: "mpro_nirmatrelvir_glide.pdb",
        processed: "mpro_nirmatrelvir_processed.pdb",
        visualization: "mpro_nirmatrelvir_viz.png",
      },
    },
    metadata: {
      createdBy: "user_002",
      createdAt: new Date("2024-01-14T15:20:00"),
      updatedAt: new Date("2024-01-14T15:30:00"),
      projectId: "proj_002",
      validated: true,
    },
  },
  {
    id: "dock_003",
    protein: {
      pdbId: "3PXF",
      name: "CDK2 Cyclin-dependent Kinase",
      uniprotId: "P24941",
      organism: "Homo sapiens",
    },
    ligand: {
      name: "Roscovitine",
      smiles: "CC(C)C(=O)Nc1ccc(cc1)N(C)C",
      molecularWeight: 354.45,
      logP: 1.8,
      hBondDonors: 2,
      hBondAcceptors: 4,
    },
    simulation: {
      program: "autodock",
      version: "4.2.6",
      parameters: { ga_num_evals: 2500000, ga_run: 10 },
      runtime: 420,
      timestamp: new Date("2024-01-13T09:15:00"),
    },
    binding: {
      affinity: -7.8,
      ki: 0.0019,
      bindingMode: 1,
      poseCount: 10,
      bestPose: {
        coordinates: [[0, 0, 0]],
        interactions: [
          { type: "hydrogen-bond", residues: ["Leu83", "Asp145"], distance: 2.9 },
          { type: "hydrophobic", residues: ["Ile10", "Val18"], distance: 3.6 },
        ],
      },
    },
    aiTags: {
      proteinFamily: ["Serine/Threonine Kinase", "CDK Family"],
      therapeuticArea: ["Oncology", "Cell Cycle"],
      bindingStrength: "moderate",
      druggability: "medium",
      noveltyScore: 0.65,
    },
    storage: {
      cid: "QmZ9mL1oP7rS0tU6vW8xY9zA2bC4dE5fG7hH8iI9jJ0kK",
      solanaTx: "7Lo0MsRpAyZb6Yt9Tr5Ov8Qw3Ns0Ou2Qr7St3Vw6Yz9",
      dataHash: "0x9c1a0b9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b",
      fileReferences: {
        original: "cdk2_roscovitine_autodock.pdb",
        processed: "cdk2_roscovitine_processed.pdb",
      },
    },
    metadata: {
      createdBy: "user_001",
      createdAt: new Date("2024-01-13T09:15:00"),
      updatedAt: new Date("2024-01-13T09:25:00"),
      projectId: "proj_003",
      validated: false,
    },
  },
  {
    id: "dock_004",
    protein: {
      pdbId: "4HJO",
      name: "BTK Kinase Domain",
      uniprotId: "Q06187",
      organism: "Homo sapiens",
    },
    ligand: {
      name: "Ibrutinib",
      smiles: "C1=CC(=CC=C1N2CCN(CC2)C(=O)C=C)NC3=NC=CC(=N3)C4=CN=CC=C4",
      molecularWeight: 440.5,
      logP: 3.7,
      hBondDonors: 1,
      hBondAcceptors: 5,
    },
    simulation: {
      program: "vina",
      version: "1.2.3",
      parameters: { exhaustiveness: 16, num_modes: 20 },
      runtime: 680,
      timestamp: new Date("2024-01-12T14:45:00"),
    },
    binding: {
      affinity: -8.9,
      ki: 0.00031,
      bindingMode: 1,
      poseCount: 20,
      bestPose: {
        coordinates: [[0, 0, 0]],
        interactions: [
          { type: "covalent", residues: ["Cys481"], distance: 1.8 },
          { type: "hydrogen-bond", residues: ["Met477", "Ser538"], distance: 2.7 },
        ],
      },
    },
    aiTags: {
      proteinFamily: ["Tyrosine Kinase", "Tec Family"],
      therapeuticArea: ["Oncology", "Hematology"],
      bindingStrength: "strong",
      druggability: "high",
      noveltyScore: 0.88,
    },
    storage: {
      cid: "QmA0nM2pQ3rS5tU7vW9xY0zA3bC5dE6fG8hH9iI0jJ1kK",
      solanaTx: "8Mp1NtSqBzZc7Yu0Us6Pw9Rx4Ot1Pv3Rs8Tu4Wx7Yz0",
      dataHash: "0x0d2b1c0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d2e1f0a9b8c7d6e5f4a3b2c",
      fileReferences: {
        original: "btk_ibrutinib_vina.pdbqt",
        processed: "btk_ibrutinib_processed.pdb",
        visualization: "btk_ibrutinib_viz.png",
      },
    },
    metadata: {
      createdBy: "user_003",
      createdAt: new Date("2024-01-12T14:45:00"),
      updatedAt: new Date("2024-01-12T14:55:00"),
      projectId: "proj_001",
      validated: true,
    },
  },
  {
    id: "dock_005",
    protein: {
      pdbId: "5WIU",
      name: "PD-1 Immune Checkpoint",
      uniprotId: "Q15116",
      organism: "Homo sapiens",
    },
    ligand: {
      name: "BMS-1001",
      smiles: "CC1=CC=C(C=C1)C2=NN=C(O2)C3=CC=CC=C3",
      molecularWeight: 275.31,
      logP: 4.1,
      hBondDonors: 0,
      hBondAcceptors: 3,
    },
    simulation: {
      program: "gromacs",
      version: "2023.1",
      parameters: { method: "molecular_dynamics", time: "100ns" },
      runtime: 14400,
      timestamp: new Date("2024-01-11T08:00:00"),
    },
    binding: {
      affinity: -6.5,
      ki: 0.017,
      bindingMode: 1,
      poseCount: 5,
      bestPose: {
        coordinates: [[0, 0, 0]],
        interactions: [
          { type: "hydrophobic", residues: ["Ile134", "Tyr68"], distance: 3.8 },
          { type: "pi-stacking", residues: ["Phe63"], distance: 3.4 },
        ],
      },
    },
    aiTags: {
      proteinFamily: ["Immunoglobulin Superfamily", "Immune Checkpoint"],
      therapeuticArea: ["Oncology", "Immunotherapy"],
      bindingStrength: "weak",
      druggability: "low",
      noveltyScore: 0.45,
    },
    storage: {
      cid: "QmB1oN3qR4sT6uV8wX0yY1zA4bC6dE7fG9hH0iI1jJ2kK",
      solanaTx: "9Nq2OuTrCaAd8Zv1Vt7Qx0Sy5Pu2Qw4St9Uv5Xy8Za1",
      dataHash: "0x1e3c2d1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f6a5b4c3d",
      fileReferences: {
        original: "pd1_bms1001_gromacs.gro",
        processed: "pd1_bms1001_processed.pdb",
      },
    },
    metadata: {
      createdBy: "user_002",
      createdAt: new Date("2024-01-11T08:00:00"),
      updatedAt: new Date("2024-01-11T12:00:00"),
      projectId: "proj_002",
      validated: false,
    },
  },
]

export const mockProjects: ResearchProject[] = [
  {
    id: "proj_001",
    name: "EGFR Inhibitor Discovery",
    description: "Comprehensive screening of novel compounds against EGFR kinase domain for lung cancer therapy",
    researchers: ["Dr. Sarah Chen", "Dr. Michael Rodriguez", "Dr. Emily Watson"],
    walletAddress: "7xKjY9pLmN3qR5sT8uV2wX4yZ6aB1cC9dE0fF",
    targets: [
      {
        id: "target_001",
        name: "EGFR",
        gene: "EGFR",
        organism: "Homo sapiens",
        uniprotId: "P00533",
        pdbIds: ["1M17", "2ITY", "3POZ"],
        pathways: ["MAPK signaling", "PI3K-Akt signaling"],
        diseaseAssociations: ["Lung cancer", "Glioblastoma", "Colorectal cancer"],
      },
    ],
    status: "active",
  },
  {
    id: "proj_002",
    name: "COVID-19 Main Protease Study",
    description: "Virtual screening campaign for SARS-CoV-2 Mpro inhibitors with antiviral potential",
    researchers: ["Dr. James Liu", "Dr. Patricia Martinez"],
    walletAddress: "8yLjZ0qMoO4rS6tU9vW3xY5zA2bC0dD1eE",
    targets: [
      {
        id: "target_002",
        name: "Main Protease",
        gene: "nsp5",
        organism: "SARS-CoV-2",
        uniprotId: "P0DTD1",
        pdbIds: ["6LU7", "7JUN", "7K3T"],
        pathways: ["Viral replication"],
        diseaseAssociations: ["COVID-19"],
      },
    ],
    status: "active",
  },
  {
    id: "proj_003",
    name: "Kinase Selectivity Panel",
    description: "Multi-target docking against human kinome for selectivity profiling",
    researchers: ["Dr. Robert Kim", "Dr. Linda Patel", "Dr. Thomas Anderson"],
    walletAddress: "9zMkA1rNpP5sT7uV0wX4yY6zA3bC1dD2eE",
    targets: [
      {
        id: "target_003",
        name: "CDK2",
        gene: "CDK2",
        organism: "Homo sapiens",
        uniprotId: "P24941",
        pdbIds: ["3PXF", "1HCL", "2C5X"],
        pathways: ["Cell cycle", "p53 signaling"],
        diseaseAssociations: ["Cancer"],
      },
    ],
    status: "completed",
  },
]

export const mockProcessingJobs: ProcessingJob[] = [
  {
    id: "job_001",
    userId: "user_001",
    filePath: "egfr_compound_library.sdf",
    status: "completed",
    result: mockDockingResults[0],
    startedAt: new Date("2024-01-15T10:30:00"),
    completedAt: new Date("2024-01-15T10:35:00"),
    createdAt: new Date("2024-01-15T10:29:00"),
  },
  {
    id: "job_002",
    userId: "user_002",
    filePath: "mpro_screening_set.pdbqt",
    status: "processing",
    startedAt: new Date("2024-01-15T11:00:00"),
    createdAt: new Date("2024-01-15T10:58:00"),
  },
  {
    id: "job_003",
    userId: "user_001",
    filePath: "kinase_panel_compounds.mol2",
    status: "pending",
    createdAt: new Date("2024-01-15T11:15:00"),
  },
]

export const mockSystemStats: SystemStats = {
  totalDataPoints: 12847,
  storageUsed: "487 GB",
  blockchainEntries: 9234,
  classificationAccuracy: "94.7%",
  processingQueue: 3,
  recentActivity: [],
}

export const mockActivities: Activity[] = [
  {
    id: "activity_001",
    type: "upload",
    user: "Dr. Sarah Chen",
    description: "Uploaded EGFR docking results (1,247 compounds)",
    timestamp: new Date("2024-01-15T10:35:00"),
    metadata: { compounds: 1247, protein: "EGFR" },
  },
  {
    id: "activity_002",
    type: "verification",
    user: "Dr. James Liu",
    description: "Verified COVID-19 Mpro dataset on blockchain",
    timestamp: new Date("2024-01-15T09:20:00"),
    metadata: { dataId: "dock_002", txHash: "6Kn9LrQoZwYa5Xs8Sq4Nu7Pv2Mr9Nt1Pq6Rs2Uv5Xy8" },
  },
  {
    id: "activity_003",
    type: "query",
    user: "Dr. Michael Rodriguez",
    description: "Searched for strong binding compounds (affinity < -8.0)",
    timestamp: new Date("2024-01-15T08:45:00"),
    metadata: { resultsCount: 234 },
  },
  {
    id: "activity_004",
    type: "classification",
    user: "AI Agent",
    description: "Classified 156 new compounds by druggability",
    timestamp: new Date("2024-01-15T07:30:00"),
    metadata: { classified: 156, accuracy: 0.947 },
  },
  {
    id: "activity_005",
    type: "upload",
    user: "Dr. Robert Kim",
    description: "Uploaded CDK2 kinase selectivity panel",
    timestamp: new Date("2024-01-14T16:15:00"),
    metadata: { compounds: 892, protein: "CDK2" },
  },
]
